#!/bin/sh
set -e

#Note: Even if your postinst doesn't do anything with debconf, you
#currently need to make sure it loads one of the debconf libraries. This
#is because the debconf libraries do deep magic to make the config
#scripts work. This will be changed in the future.

case "${1}" in
    #The config script is run before the package is unpacked.
    reconfigure)
        #workaround for the hacky way of managing configure/reconfigure in maintainer scripts/debconf
        if [ -f /var/lib/dpkg/info/mozilla-minos-settings.postinst ]; then
            /var/lib/dpkg/info/mozilla-minos-settings.postinst configure
            true
        fi
        ;;
    abort-upgrade|abort-deconfigure|abort-remove|configure)
        ;;
    *)
        printf "%s\\n" "${0} called with unknown argument \`${1}'" 1>&2
        exit 1
        ;;
esac

#DEBHELPER#
exit 0
